FROM openwrt/sdk:x86-64-24.10.3

ARG sentinel_VERSION
ENV sentinel_VERSION=${sentinel_VERSION}

WORKDIR /builder

COPY ./sentinel package/feeds/utilities/sentinel
COPY ./luci-app-sentinel package/feeds/luci/luci-app-sentinel

RUN ./scripts/feeds update -a && \
    ./scripts/feeds install -a && \
    make defconfig && \
    make package/sentinel/compile -j1 V=s && \
    make package/luci-app-sentinel/compile -j1 V=s
