FROM openwrt/sdk:x86-64-24.10.3

ARG sentinel_VERSION
ENV sentinel_VERSION=${sentinel_VERSION}

RUN ./scripts/feeds update -a && \
    ./scripts/feeds install -a

COPY ./sentinel /builder/package/feeds/utilities/sentinel
COPY ./luci-app-sentinel /builder/package/feeds/luci/luci-app-sentinel

RUN make defconfig && \
    make package/sentinel/compile -j1 V=s

RUN make package/luci-app-sentinel/compile -j1 V=s
