include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-sentinel
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Sentinel
LUCI_DEPENDS:=+luci-base +sentinel
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk
