name: Build sentinel and luci-app-sentinel

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build OpenWrt packages
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: sentinel:ci
          build-args: |
            PKG_VERSION=${{ env.VERSION }}

      - name: Create Docker container
        run: docker create --name sentinel sentinel:ci

      - name: Copy build artifacts
        run: |
          mkdir -p bin filtered-bin
          docker cp sentinel:/builder/bin/packages/x86_64/utilites/. ./bin/
          docker cp sentinel:/builder/bin/packages/x86_64/luci/. ./bin/

          cp ./bin/sentinel_*.ipk ./filtered-bin/
          cp ./bin/luci-app-sentinel_*.ipk ./filtered-bin/
          cp ./bin/luci-i18n-sentinel-ru_*.ipk ./filtered-bin/ || true

      - name: Remove Docker container
        run: docker rm sentinel

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-ipk-${{ env.VERSION }}
          path: filtered-bin/

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: filtered-bin/*.ipk
